import pickle
import pandas as pd
import xgboost as xgb
import math
import datetime
import codecs

from flask import jsonify

"""
https://dshung.shinyapps.io/UGIB_App_USA/
https://dshung.shinyapps.io/UGIB_App_INTL/

Upper Gastrointestinal Bleeding (UGIB) Studies Summary
* reported annual incidences in the range of 48 to 172 per 100,000
* need_of_hospital_based_intervention means a composite endpoint of hospital-based intervention (transfusion or hemostatic intervention) or death within 30 days
* study samples from United States, Scotland, England, Denmark; n=1958 and Singapore and New Zealand; n=399
* pre-endoscopic clinical risk scores: Glasgow-Blatchford 6.53, Admission-Rockall 2.82, AIMS65 1.0
"""

# Input data set statistics
means = {'Age': 62.72490, 'Pulse': 91.51025, 'Systolic Blood Pressure': 127.21670, 'Hemoglobin': 112.91685, 'Albumin': 35.85830,
'Urea': 2.108966, 'Creatinine': 4.457472, 'INR': 1.134330} 
sd = {'Age': 20.064903, 'Pulse': 20.267430, 'Systolic Blood Pressure': 24.111854, 'Hemoglobin': 32.191806, 'Albumin': 7.229249,
'Urea': 0.7763588, 'Creatinine': 0.5101569, 'INR': 0.3375174}

fhir_inputs = ['Age', 'Pulse', 'Systolic Blood Pressure', 'Hemoglobin', 'Urea', 'Creatinine', 'Albumin', 'INR', 'Sex', 'Syncope',
'Altered Mental Status', 'Ischemic Heart Disease', 'Cardiac Failure', 'Renal Failure', 'Any Malignancy', 'Liver', 'ASA Score',
'Hematemesis', 'Melena', 'Hematochezia', 'Aspirin', 'Adenosine Diphosphate Inhibitors', 'Anticoagulation', 'NSAIDs']

model_inputs = ['age', 'pulse', 'systolicbloodpressure', 'haemoglobin', 'urea', 'creatinine', 'albumin', 'inr', 'sex', 'syncope',
'alteredmentalstatus', 'ischaemicheartdisease', 'cardiacfailure', 'renalfailure', 'malignancy_all', 'liver_categ', 'asascore',
'haemetemesis', 'melaena', 'haematochezia', 'Aspirin', 'adp_inhibitors', 'Anticoagulant', 'nsaids']

def getParams(p):
    # Demographic (2)
    # Age 62.7 (18-106) 
    # Sex 58% (male, female)
    if 'Birth Date' in p:
        bdate = datetime.date(*(int(s) for s in p['Birth Date'].split('-')))
        today = datetime.date.today()
        p['Age'] = today.year - bdate.year - ((today.month, today.day) < (bdate.month, bdate.day))
    else: p['Age'] = means['Age'] # set default to mean value
    if 'Gender' in p and p['Gender'] == 'male': p['Sex'] = 1 # model accept male as 1
    else: p['Sex'] = 0 # default to female and model accept female as 0
    # Comorbidity (6)
    # ASA Score 1 12% 2 30% 3 47% 4 9.9% 5 0.8%
    if not 'ASA Score' in p or not p['ASA Score'] in ['1','2','3','4','5']: p['ASA Score'] = 1
    # Liver 0 81% 1 5% 2 6% 3 9% 0=no liver disease, 1=liver disease, 2=liver cirrhosis, 3=liver failure
    if not 'Liver' in p or not p['Liver'] in ['0','1','2','3']: p['Liver'] = 0
    for key in ['Ischemic Heart Disease','Cardiac Failure','Renal Failure','Any Malignancy']:
        if not key in p: p[key] = 0 # set default to no condition
        else: p[key] = 1 # model accept condition as 1
    # Medications (4)
    for key in ['Aspirin','Adenosine Diphosphate Inhibitors','Anticoagulation','NSAIDs']:
        if not key in p: p[key] = 0 # set default to no condition
        else: p[key] = 1 # model accept condition as 1
    # Clinical Features at Presentation (7)
    for key in ['Pulse','Systolic Blood Pressure']:
        if not key in p: p[key] = means[key] # set default to mean value
        elif type(p[key]) == str: p[key] = p[key].split()[0] # remove unit if any
    for key in ['Syncope','Altered Mental Status','Hematemesis','Melena','Hematochezia']:
        if not key in p: p[key] = 0 # set default to no condition
        else: p[key] = 1 # model accept condition as 1
    # Initial Laboratory Values (5)
    for key in ['Hemoglobin','Albumin','Urea','Creatinine','INR']:
        if not key in p: p[key] = means[key] # set default to mean value
        elif type(p[key]) == str: p[key] = p[key].split()[0] # remove unit if any
    return p
    
def ugibRisk(req):
    json = req.get_json()
    if not json: return cf_res()
    
    p = getParams(json['data'])

    # Normalization of inputs
    normalized_inputs = []

    for name in fhir_inputs:
        raw_value = float(p[name])

        if name in ['Age', 'Pulse', 'Systolic Blood Pressure', 'Hemoglobin', 'Albumin']:
            normalized_value = (raw_value - means[name]) / sd[name]
        elif name in ['Urea', 'Creatinine']:
            normalized_value = (math.log(raw_value) - means[name]) / sd[name]
        elif name == 'INR':
            normalized_value = (math.sqrt(raw_value) - means[name]) / sd[name]
        else:
            normalized_value = raw_value

        normalized_inputs.append(normalized_value)

    # Create Pandas DataFrame
    input_variables = pd.DataFrame([normalized_inputs], columns=model_inputs, dtype=float)
    
    # Perform model prediction on inputs
    model = pickle.loads(codecs.decode(pmodel.encode(), "base64"))
    prediction = model.predict(xgb.DMatrix(input_variables))[0]
    
    return cf_res({ 'risk': str(prediction) })

def cf_res(r = ''):
    res = jsonify({ 'data': r })
    res.headers['Access-Control-Allow-Origin'] = '*'
    res.headers['Access-Control-Allow-Headers'] = 'Content-Type,Authorization'
    res.headers['Access-Control-Allow-Methods'] = 'GET,POST,OPTIONS'
    return res

pmodel = "gANjeGdib29zdC5jb3JlCkJvb3N0ZXIKcQApgXEBfXECKFgNAAAAZmVhdHVyZV9uYW1lc3EDXXEE\
KFgDAAAAYWdlcQVYBQAAAHB1bHNlcQZYFQAAAHN5c3RvbGljYmxvb2RwcmVzc3VyZXEHWAsAAABo\
YWVtb2dsb2JpbnEIWAQAAAB1cmVhcQlYCgAAAGNyZWF0aW5pbmVxClgHAAAAYWxidW1pbnELWAMA\
AABpbnJxDFgDAAAAc2V4cQ1YBwAAAHN5bmNvcGVxDlgTAAAAYWx0ZXJlZG1lbnRhbHN0YXR1c3EP\
WBUAAABpc2NoYWVtaWNoZWFydGRpc2Vhc2VxEFgOAAAAY2FyZGlhY2ZhaWx1cmVxEVgMAAAAcmVu\
YWxmYWlsdXJlcRJYDgAAAG1hbGlnbmFuY3lfYWxscRNYCwAAAGxpdmVyX2NhdGVncRRYCAAAAGFz\
YXNjb3JlcRVYDAAAAGhhZW1ldGVtZXNpc3EWWAcAAABtZWxhZW5hcRdYDQAAAGhhZW1hdG9jaGV6\
aWFxGFgHAAAAQXNwaXJpbnEZWA4AAABhZHBfaW5oaWJpdG9yc3EaWA0AAABBbnRpY29hZ3VsYW50\
cRtYBgAAAG5zYWlkc3EcZVgNAAAAZmVhdHVyZV90eXBlc3EdXXEeKFgFAAAAZmxvYXRxH2gfaB9o\
H2gfaB9oH2gfWAMAAABpbnRxIGggaCBoIGggaCBoIGggaCBoIGggaCBoIGggaCBoIGVYBgAAAGhh\
bmRsZXEhY2J1aWx0aW5zCmJ5dGVhcnJheQpxIkI9TwAAAAAAgBgAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8A\
AAAAAAAAYmluYXJ5OmxvZ2lzdGljBgAAAAAAAABnYnRyZWUKAAAAAQAAABgAAAAAAAAAAAAAAAAA\
AAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAADUAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AP////8BAAAAAgAAAAMAAICZb5S+AAAAgAMAAAAEAAAAAwAAgGlnf78AAAAABQAAAAYAAAAEAACA\
CHEFPwEAAIAHAAAACAAAAAAAAIBY5uO/AQAAAAkAAAAKAAAABAAAgHDkDb4CAACACwAAAAwAAAAH\
AACA7g2GPgIAAAANAAAADgAAAAUAAIAY9wI/AwAAgP//////////AAAAAMNkKrwDAAAADwAAABAA\
AAADAACAgLs3wAQAAIARAAAAEgAAAAEAAIB9UJc+BAAAABMAAAAUAAAABwAAgBqTz74FAACAFQAA\
ABYAAAADAACAov3lPQUAAAAXAAAAGAAAAAYAAIAUZkC+BgAAgBkAAAAaAAAABwAAgBDc3r4GAAAA\
GwAAABwAAAAHAACAETO1vAgAAID//////////wAAAADDZCq8CAAAAP//////////AAAAAPZIUD0J\
AACAHQAAAB4AAAACAACA/ISIvwkAAAAfAAAAIAAAABAAAIAAACBACgAAgCEAAAAiAAAABgAAgPoB\
S70KAAAAIwAAACQAAAAEAACA/xgNQAsAAIAlAAAAJgAAAA4AAIAAAAA/CwAAACcAAAAoAAAAAQAA\
gGtUJ0AMAACAKQAAACoAAAAGAACACme3vwwAAAArAAAALAAAAAQAAIAoC1M+DQAAgC0AAAAuAAAA\
BQAAgC6k6b4NAAAALwAAADAAAAAFAACAAkL2vg4AAIAxAAAAMgAAAAQAAIBoNro/DgAAADMAAAA0\
AAAAAgAAgPssLL8RAACA//////////8AAAAAo/6NPBEAAAD//////////wAAAAAFMeO8EgAAgP//\
////////AAAAAA2hwbwSAAAA//////////8AAAAAiJC2PBMAAID//////////wAAAAD0/dQ8EwAA\
AP//////////AAAAACWXf7wUAACA//////////8AAAAAGT0GPRQAAAD//////////wAAAACj/o28\
FQAAgP//////////AAAAAN393bwVAAAA//////////8AAAAA6VgWPBYAAID//////////wAAAABK\
aDu9FgAAAP//////////AAAAAKP+jTwXAACA//////////8AAAAAo/6NvBcAAAD//////////wAA\
AAD0/dQ8GAAAgP//////////AAAAAKP+Db0YAAAA//////////8AAAAAo/6NPBkAAID/////////\
/wAAAABha/M7GQAAAP//////////AAAAAPT91LwaAACA//////////8AAAAAAAAAgBoAAAD/////\
/////wAAAABxhQY9GwAAgP//////////AAAAALMxHL0bAAAA//////////8AAAAAo/4NPBwAAID/\
/////////wAAAAC9dBM9HAAAAP//////////AAAAAGFrc7xe4adDAMBzQ51dPr4AAAAACMkTQgCA\
wULCaKA/AAAAAJDlIUIAABNDHEyRvwAAAACAE0NAAAAzQgrP9D8BAAAAY1SDQQAAUEJ+Dik/AAAA\
AOgFwEEAgOhCBJWzvwAAAACD8nFBAAD2QYfD4b0AAAAAAAAAAAAAgD7NzMy+AAAAAEDMRUAAADJC\
eY/3PwIAAAA/6ddAAABsQTmOY74AAAAAAH63QAAAFUIs1oA/AAAAAABeQEEAgM1CYHvIvwAAAABj\
pSBBAABYQcs9Db4AAAAAZ4nxQAAAXEGh4SQ/AAAAAERIHUEAAIhBjuM4vwAAAAAAAAAAAACAPs3M\
zL4AAAAAAAAAAAAAMUKxV/o/AAAAANDMREAAAOBAAABgvwIAAACrf8BAAAD4QM3MzD4CAAAAtmDL\
QAAAAEE5jmM+AgAAAIA7eUAAAOpBP3KaPwIAAAAGk8FAAACgQfQ8T78CAAAA4Ce2QACApUJJYN6/\
AgAAABzHsUAAAABB5DgOPwIAAAAw33JAAACwQJ7Yib8CAAAAz/O8PwAAMECrqiq/AgAAAPQaSkAA\
ADBBAACAPwIAAAAc18xAAABEQWG8lb8CAAAAZizJQAAAmEDTm94+AgAAAAAAAAAAAAA/q6oqPwAA\
AAAAAAAAAADQQImIiL8AAAAAAAAAAAAA4D8vumi/AAAAAAAAAAAAAMBAt21bPwAAAAAAAAAAAACA\
QAAAgD8AAAAAAAAAAAAAgECamRm/AAAAAAAAAAAAAOZBNFihPwAAAAAAAAAAAAAAP6uqKr8AAAAA\
AAAAAAAAhkGQaIW/AAAAAAAAAAAAAFBAtbS0PgAAAAAAAAAAAICkQs8/4b8AAAAAAAAAAAAAAD+r\
qio/AAAAAAAAAAAAAABAq6oqvwAAAAAAAAAAAADAQAAAgD8AAAAAAAAAAAAAoECrqqq/AAAAAAAA\
AAAAAAA/q6oqPwAAAAAAAAAAAABAPyVJkj4AAAAAAAAAAAAAAEAAAIC/AAAAAAAAAAAAACBAAAAA\
gAAAAAAAAAAAAAAIQSivoT8AAAAAAAAAAAAAJEG8u7u/AAAAAAAAAAAAAABAq6qqPgAAAAAAAAAA\
AAAQQBQ7sT8AAAAAAAAAAAAAIEAlSRK/AAAAAAEAAAA5AAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAD/////AQAAAAIAAAADAACA/m4MvgAAAIADAAAABAAAAAMAAIDahUO/AAAAAAUAAAAGAAAA\
BAAAgNdhHj4BAACABwAAAAgAAAADAACAgLs3wAEAAAAJAAAACgAAAAQAAIBrZfc9AgAAgAsAAAAM\
AAAABwAAgO4Nhj4CAAAADQAAAA4AAAAIAACAAAAAPwMAAID//////////wAAAAAsgim8AwAAAA8A\
AAAQAAAABgAAgOZTE0AEAACAEQAAABIAAAABAACAk6qaPwQAAAATAAAAFAAAAAIAAIAbEAU9BQAA\
gBUAAAAWAAAABgAAgMiq478FAAAAFwAAABgAAAAGAACAFGZAvgYAAIAZAAAAGgAAAAUAAIBaTke/\
BgAAABsAAAAcAAAAAwAAgM5fVz8IAACAHQAAAB4AAAADAACAaWd/vwgAAAAfAAAAIAAAAAAAAIAM\
/iI/CQAAgCEAAAAiAAAABgAAgBeKA8AJAAAAIwAAACQAAAAAAACAsVTavwoAAIAlAAAAJgAAAAcA\
AICe5gS/CgAAACcAAAAoAAAAEgAAgAAAAD8LAACAKQAAACoAAAACAACA/LQBvwsAAAArAAAALAAA\
ABAAAIAAAGBADAAAgC0AAAAuAAAAAAAAgEdXgT8MAAAALwAAADAAAAAUAACAAAAAPw0AAIAxAAAA\
MgAAAAQAAIDACeo+DQAAADMAAAA0AAAADgAAgAAAAD8OAACANQAAADYAAAACAACAfTHTPw4AAAA3\
AAAAOAAAAAUAAIAg9OM+DwAAgP//////////AAAAAEEKQT0PAAAA//////////8AAAAA2fsFPRAA\
AID//////////wAAAACVCSi8EAAAAP//////////AAAAAGwVJjwRAACA//////////8AAAAApKer\
PBEAAAD//////////wAAAABI2tm8EgAAgP//////////AAAAAFkXKLwSAAAA//////////8AAAAA\
w30EPRMAAID//////////wAAAABSygu8EwAAAP//////////AAAAAL9iLz0UAACA//////////8A\
AAAAcVyDvBQAAAD//////////wAAAABBYr08FQAAgP//////////AAAAAH6DJrwVAAAA////////\
//8AAAAA95iQPBYAAID//////////wAAAABGZjm9FgAAAP//////////AAAAALXmhrwXAACA////\
//////8AAAAAYHvfPBcAAAD//////////wAAAAA+2Y+8GAAAgP//////////AAAAACvlAL0YAAAA\
//////////8AAAAA8g0APBkAAID//////////wAAAAB+gya8GQAAAP//////////AAAAAGL4tzwa\
AACA//////////8AAAAA5pcHvRoAAAD//////////wAAAAA+Y8i7GwAAgP//////////AAAAAPkL\
QzwbAAAA//////////8AAAAA7dDovBwAAID//////////wAAAABbw1y7HAAAAP//////////AAAA\
AJviD73ur5tDyadtQ4O/QL4AAAAAenQxQj5r1kIk0og/AAAAACgu+0EqcgJD+GCcvwAAAACAECRA\
+eBjQqY91T8BAAAAVcrPQYP1SEIyxr4+AAAAAHC4fEG86rJCxaXGvwAAAABuN89AMfMjQhxc9r4A\
AAAAAAAAADr+fz51vMu+AAAAAAAIuT/74GJCdkTXPwAAAAD32z5BC/mhQeIO+r4AAAAAXDz1QPvx\
70ENaXM/AAAAAMAWhEDHa6FCai/YvwAAAACbgfJAo/cLQTUaer4AAAAA9ERrQFnte0Fw2Xa/AAAA\
AGGcIkG178lBP0gevgAAAAAAvyE/MuFgQh4p2T8CAAAAW9jEPobk/z6zcHy7AgAAABqo00BH+odB\
El1TvwIAAACsCdQ/GvZPQD0Fhz8CAAAASLP9QH34gUEUDbM/AgAAAIB4AkH88ltBvIu5PgIAAAA6\
zjg/2us/P6L8mj4CAAAAAHG/P/Drn0JDBtu/AgAAAB40N0Ao929AzLs5PwIAAAB0+gtAsvOfQN2q\
eL8CAAAA3Cd5P9zufz/i8QI/AgAAAHhdCkBs7mtBjpOLvwIAAACcHZZAa/aHQUEwlD4CAAAALAwp\
QJXyA0GvP4C/AgAAAAAAAACH5CdC8AToPwAAAAAAAAAArvJjQccJoT8AAAAAAAAAAGXzfz7T98m+\
AAAAAAAAAACn1X8+q57HPgAAAAAAAAAAbvq/P+BQTj8AAAAAAAAAAEH1d0HL64K/AAAAAAAAAAD4\
838+XgjKvgAAAAAAAAAA2vY/QIo+nz8AAAAAAAAAAHj4/z9nBKi+AAAAAAAAAADs8WNB18zSPwAA\
AAAAAAAA9PaXQM3iHb8AAAAAAAAAAIL3D0Hwn2M/AAAAAAAAAAC43X8+9yLIvgAAAAAAAAAA2Oj/\
PovLLT8AAAAAAAAAAKxsmkIA1t6/AAAAAAAAAABu6C9ADyQivwAAAAAAAAAAi/hPQNZNhj8AAAAA\
AAAAAO30/z4c5Sy/AAAAAAAAAACK9YdAD+yavwAAAAAAAAAAPPE/P2DpmT4AAAAAAAAAALjdfz73\
Isi+AAAAAAAAAABu9z8/Ox5dPwAAAAAAAAAAhPE7QQj5or8AAAAAAAAAAJ7zP0C+2XC+AAAAAAAA\
AABb7ntBZG7qPgAAAAAAAAAAzvOfP93pi78AAAAAAAAAALbvL0COqwS+AAAAAAAAAABQ7a9AXPCs\
vwAAAAABAAAANQAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wEAAAACAAAAAwAAgABh\
/74AAACAAwAAAAQAAAADAACATy8xvwAAAAAFAAAABgAAAAYAAIAgGLs+AQAAgAcAAAAIAAAAAwAA\
gAb1PsABAAAACQAAAAoAAAAGAACALMq1PQIAAIALAAAADAAAAAIAAID526O+AgAAAA0AAAAOAAAA\
AwAAgHZOLL4DAACA//////////8AAAAAOqEovAMAAAAPAAAAEAAAAAIAAID/pRc/BAAAgBEAAAAS\
AAAADwAAgAAAAD8EAAAAEwAAABQAAAACAACA//QcPwUAAIAVAAAAFgAAAAQAAIDyUTM+BQAAABcA\
AAAYAAAABwAAgDDIPz8GAACAGQAAABoAAAACAACA/5fvPgYAAAAbAAAAHAAAAAQAAIC2NR8/CAAA\
gP//////////AAAAACoZOz0IAAAAHQAAAB4AAAADAACA9vphvwkAAIAfAAAAIAAAAAAAAIChkLc/\
CQAAACEAAAAiAAAABwAAgPHM67wKAACAIwAAACQAAAACAACAe1WwvwoAAAD//////////wAAAAD9\
bNA8CwAAgCUAAAAmAAAADwAAgAAAIEALAAAAJwAAACgAAAAFAACAbG2jPgwAAIApAAAAKgAAAAQA\
AIDQp6+7DAAAACsAAAAsAAAAAgAAgAAgxT4NAACALQAAAC4AAAAXAACAAAAAPw0AAAAvAAAAMAAA\
AAMAAIDY7Gu+DgAAgDEAAAAyAAAAAQAAgM98KkAOAAAAMwAAADQAAAAFAACAEJSMvhAAAID/////\
/////wAAAAA0rx49EAAAAP//////////AAAAAJYaL7wRAACA//////////8AAAAAcJ0uPREAAAD/\
/////////wAAAAClTpG8EgAAgP//////////AAAAAMETtDwSAAAA//////////8AAAAA+XTsvBMA\
AID//////////wAAAACAavg7EwAAAP//////////AAAAANIw7LwVAACA//////////8AAAAA58Kx\
vBUAAAD//////////wAAAAB7EKE8FgAAgP//////////AAAAAIyL4TwWAAAA//////////8AAAAA\
OpiNuxcAAID//////////wAAAABj7hK9FwAAAP//////////AAAAAMUferwYAACA//////////8A\
AAAA+bONvBgAAAD//////////wAAAAA7V9M8GQAAgP//////////AAAAAGz37jwZAAAA////////\
//8AAAAAdLONvBoAAID//////////wAAAACRqRe9GgAAAP//////////AAAAAL6sKzwbAACA////\
//////8AAAAAVh4wvRsAAAD//////////wAAAACexyw8HAAAgP//////////AAAAAL/NJzwcAAAA\
//////////8AAAAAakLuvLaarENqpXpDt5AavgAAAACgYn1BDTWsQsAHuz8AAAAAfJQNQuSKJEM7\
j3+/AAAAAMA5IEDfOZJCDwLSPwEAAADK1sxAatlPQUfDzz4AAAAAhVeBQSTWqUKqHAq/AAAAAEC6\
DkGjP59CSca8vwAAAAAAAAAA8/h/Pheuyr4AAAAAAKEXQOO5kUKFk9M/AQAAAEYOqEAryfdApwtw\
PwAAAAAW+JZAqumnQL6gzr4BAAAA0zkGQQHjAUKhY4c8AAAAAHSZA0FHyVFCEqxgvwAAAADwaORA\
Xuu3QDeJa74AAAAAwGA1QO3Ak0KQnMi/AAAAAAAAAABSim5CteDgPwAAAAB8hRFBzqVTQdwEjD8C\
AAAAcJKcQJDSt0D06K4/AgAAAIFZa0Br2v8/ssStvgIAAAAS/+0/eu6HQOBuWr8CAAAAAAAAAHvZ\
fz//gno/AAAAAPkz8kBLt3dBjKn/vgIAAADbodxAXeqHQZ78+T4CAAAAqEzUQPXLOkJD04G/AgAA\
AHzHqECL6rdAGJdfPgIAAAAALjtAqeY/QKhqOz8CAAAAkEz5PxPwL0Cu7pi/AgAAAIBsI0DqwoRC\
ve7RvwIAAAAGhmhAOuDvQF4nTr8CAAAAAAAAAIurJ0H3ub4/AAAAAAAAAAAN6S9AG3bSvgAAAAAA\
AAAAodWnQLDf0T8AAAAAAAAAAPDO/z7ppS6/AAAAAAAAAAAe5z8/W3BYPwAAAAAAAAAA3OafP/0Z\
jr8AAAAAAAAAAKrzPz/ZSZU+AAAAAAAAAAAK4F9ACPGNvwAAAAAAAAAAs75HQcynVb8AAAAAAAAA\
AF3iP0BFlkE/AAAAAAAAAAAv7QtBP4uHPwAAAAAAAAAAi+cDQZQvKr4AAAAAAAAAABG3v0GZmbC/\
AAAAAAAAAADa4LVBoVAWvwAAAAAAAAAAkO4vQO1QKr8AAAAAAAAAAIbmP0DrA34/AAAAAAAAAACC\
5x9AE5yPPwAAAAAAAAAANfn/Pk5QKr8AAAAAAAAAAE7wH0BYSba/AAAAAAAAAABP/H8+AlfOPgAA\
AAAAAAAA8EKEQk+u078AAAAAAAAAADjzfz4Aq88+AAAAAAAAAAAY9L8/6K/JPgAAAAAAAAAANOO/\
QEwvj78AAAAAAQAAADMAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////8BAAAAAgAAAAMA\
AIAuM/W+AAAAgAMAAAAEAAAAAwAAgPSLP78AAAAABQAAAAYAAAAHAACA7g2GPgEAAIAHAAAACAAA\
AAMAAIAG9T7AAQAAAAkAAAAKAAAABAAAgBYHaz4CAACACwAAAAwAAAAEAACA8FsJPwIAAAANAAAA\
DgAAABAAAIAAAGBAAwAAgP//////////AAAAAO3BJ7wDAAAADwAAABAAAAACAACAfigAQAQAAIAR\
AAAAEgAAAAMAAIDnbxi/BAAAABMAAAAUAAAABgAAgCzKtT0FAACAFQAAABYAAAAGAACAIoXsvwUA\
AAAXAAAAGAAAAAUAAIAeF88+BgAAgBkAAAAaAAAABwAAgByd4z4GAAAAGwAAABwAAAAHAACAhij1\
PggAAID//////////wAAAACKIzg9CAAAAB0AAAAeAAAAAQAAgMlHN78JAACAHwAAACAAAAABAACA\
eCxdvwkAAAAhAAAAIgAAAAgAAIAAAAA/CgAAgCMAAAAkAAAABgAAgBb20b8KAAAAJQAAACYAAAAH\
AACAXv3HvgsAAIAnAAAAKAAAAAUAAIB0eGy/CwAAACkAAAAqAAAABAAAgN6Ru74MAACAKwAAACwA\
AAAHAACAXv3HvgwAAAAtAAAALgAAAA4AAIAAAAA/DQAAgC8AAAAwAAAABAAAgAk8Qb8NAAAAMQAA\
ADIAAAABAACAFytMvQ4AAID//////////wAAAABMC7S8DgAAAP//////////AAAAACHeKj0QAACA\
//////////8AAAAAUxYvvBAAAAD//////////wAAAACIsKs8EQAAgP//////////AAAAAFE3BjwR\
AAAA//////////8AAAAAlMwdvRIAAID//////////wAAAABxGmy8EgAAAP//////////AAAAAO6m\
qDwTAACA//////////8AAAAAbVmruhMAAAD//////////wAAAACU1h89FAAAgP//////////AAAA\
AP1qxbwUAAAA//////////8AAAAABvDjPBUAAID//////////wAAAABNbN+7FQAAAP//////////\
AAAAAA/uAT0WAACA//////////8AAAAAxHwzvRYAAAD//////////wAAAAAlR+28FwAAgP//////\
////AAAAAAXGiLsXAAAA//////////8AAAAAh1IoPRgAAID//////////wAAAABcfdO8GAAAAP//\
////////AAAAAOHzSDwZAACA//////////8AAAAAkCOTORkAAAD//////////wAAAACeDBY9GgAA\
gP//////////AAAAAACs7bwaAAAA//////////8AAAAA/AN+O9ximUMFSnNDdXx9vgAAAAD4JNNB\
Fm6aQlitsT8AAAAAyPgTQvoSJkMogoG/AAAAAACpJkCj9W5CGaDZPwEAAAAklSlBD82LQT3lkj4A\
AAAACAHvQemXD0OERJm/AAAAAIJQ+ECO2LNB3IUyPgAAAAAAAAAAOPB/PrOhyb4AAAAAAGiNPrP1\
bULykNs/AQAAAPm9RkDx1d9A1XYdvwAAAAAgF2RAJq8nQXjbYz8AAAAAUA5jQa476ULsKLW/AAAA\
AHKPXEGP0NdBRjp0vgAAAABC1wpBGt6LQYTIHb4AAAAAdDTXQM/pn0CsJ5Q/AgAAAAAAAADX+GlC\
GVLdPwAAAAAEEXI/HTd/P6Vg5T4CAAAAULA3QODPb0BE4JC/AgAAAMsyF0AD3E9ALIjbPQIAAACA\
10VADnfvQAFUnD8CAAAAc8udQHvOP0COEhK9AgAAACgw4z+B6Q9AzSBMPwIAAACgUOFAYrzkQpmQ\
u78CAAAADHcLQXjqI0GOOCM/AgAAAIzfpUBS24VBr9ZHvwIAAADG3gFAvbh/QK3mfT8CAAAA2F29\
QATOV0HW3wm/AgAAAAAAAABOzT8/MWZYvwAAAAAAAAAAJvCHQKxezT8AAAAAAAAAANTOfz78cNK+\
AAAAAAAAAABoQz8/kFtOPwAAAAAAAAAAecE/P0FRoT4AAAAAAAAAAIHfP0CUqb2/AAAAAAAAAABC\
1t8/leMNvwAAAAAAAAAAxOG/P/K0Sj8AAAAAAAAAAAOPvz/e8k29AAAAAAAAAABOk79A/BzAPwAA\
AAAAAAAAm+PfP/pHbb8AAAAAAAAAAFu5nz9S+4g/AAAAAAAAAADK2T8/x0SGvgAAAAAAAAAAHua/\
P28qnD8AAAAAAAAAADL6h0Liute/AAAAAAAAAABfhDlCS5iOvwAAAAAAAAAA8e6/QChkJL4AAAAA\
AAAAAADmh0B/T8o/AAAAAAAAAAABvWdBwDF+vwAAAAAAAAAAj+YPQJaH8T4AAAAAAAAAAIfGvz+D\
2TA8AAAAAAAAAAB61R9AA1m0PwAAAAAAAAAAHszfQOfUjr8AAAAAAAAAAOvPz0BRpxg+AAAAAAEA\
AAAzAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AQAAAAIAAAADAACAZqoDvwAAAIAD\
AAAABAAAAAMAAIC07km/AAAAAAUAAAAGAAAABAAAgPiwob0BAACABwAAAAgAAAADAACABvU+wAEA\
AAAJAAAACgAAAAAAAICSP0K/AgAAgAsAAAAMAAAABgAAgG/Q2r8CAAAADQAAAA4AAAAHAACAGFuF\
vgMAAID//////////wAAAABA5Ca8AwAAAA8AAAAQAAAABAAAgCjHLr8EAACAEQAAABIAAAAAAACA\
it2wvwQAAAATAAAAFAAAAAAAAICIL7E/BQAAgBUAAAAWAAAAAAAAgDBvur8FAAAAFwAAABgAAAAQ\
AACAAABgQAYAAIAZAAAAGgAAAAkAAIAAAAA/BgAAABsAAAAcAAAAAQAAgFv7oD8IAACAHQAAAB4A\
AAABAACA+LCEvwgAAAAfAAAAIAAAAAIAAIB+KABACQAAgP//////////AAAAAEVEijwJAAAA////\
//////8AAAAAeAb1vAoAAIAhAAAAIgAAAAYAAIAsyrU9CgAAACMAAAAkAAAAAQAAgJJ2pL4LAACA\
//////////8AAAAAewSOvAsAAAAlAAAAJgAAAAMAAIDos9q+DAAAgCcAAAAoAAAAAwAAgP5uDL4M\
AAAAKQAAACoAAAAEAACAvjxQvw0AAIArAAAALAAAABAAAIAAAJBADQAAAC0AAAAuAAAAFAAAgAAA\
AD8OAACALwAAADAAAAAGAACAntjtvg4AAAAxAAAAMgAAABAAAIAAAMA/DwAAgP//////////AAAA\
AKu3nrwPAAAA//////////8AAAAAU38NPRAAAID//////////wAAAACuvTE9EAAAAP//////////\
AAAAAEt6PzwTAACA//////////8AAAAAoJgRPRMAAAD//////////wAAAABrfso6FAAAgP//////\
////AAAAABV6VDwUAAAA//////////8AAAAAbXDavBYAAID//////////wAAAADDSiS8FgAAAP//\
////////AAAAAArtAD0XAACA//////////8AAAAAEn2jvBcAAAD//////////wAAAADLzyu9GAAA\
gP//////////AAAAAH7WsbwYAAAA//////////8AAAAAvHY3PBkAAID//////////wAAAAABPuy8\
GQAAAP//////////AAAAACaHjDwaAACA//////////8AAAAAXKAevBoAAAD//////////wAAAABP\
tQU9GwAAgP//////////AAAAAGbRgzwbAAAA//////////8AAAAATsBSvBwAAID//////////wAA\
AAApRou8HAAAAP//////////AAAAAEQBCj1jwJFDl312Q9Cdg74AAAAAcMlAQZIDmkL1M6w/AAAA\
AJB6JELOeylD+R59vwAAAABAXBdAJjxnQmJqyT8BAAAAn4OaQPyVmUHDPh0/AAAAAECokUHgRMVC\
rayzvwAAAABYwJhBvbKNQkOUzL4AAAAAAAAAABnkfz5Dl8i+AAAAAABYxD9CPGZCbljLPwAAAAA4\
xy5APGf/P7FgIr8CAAAA1L1rQImfiUGXM0k/AAAAAHMXLUDj1V9AOPMtPwEAAABgoAdBMUa+QqJH\
vr8AAAAA4OwPQWGfFEKtX2K/AAAAAJr+BEEYxgZC0YAUPgAAAADpmMdAqsK2QGRWVT8CAAAAAFQx\
Pu1jT0JgxtM/AgAAAAAAAADCI/8+mC8mPwAAAAAAAAAATJ6/PzJAk78AAAAA4py+QDBNc0FYoHI/\
AgAAAM+oDkAHj/8/ufazvgIAAAAAAAAA/7n/PrGxKr8AAAAA3E/IP6PeP0DT2YE/AgAAAIAEb0Az\
S7dCV6jFvwIAAABqNPQ/rF9fQJNTCj0CAAAA4BpZQKSoAkIPGoi/AgAAANyTgkDntY9AX6q/PgIA\
AABXvwNBPKDZQYhC3b0CAAAASLxqQNOvz0DjDIo/AgAAAAAAAADULZ8/I8Q+vwAAAAAAAAAANveO\
QKYRqj8AAAAAAAAAAAhnS0KFodU/AAAAAAAAAAAQOX8/NyTmPgAAAAAAAAAAfWofQdT+rj8AAAAA\
AAAAAGfFp0DKYXM9AAAAAAAAAAAPdX8/gGH/PgAAAAAAAAAA/6h/PwZGg78AAAAAAAAAAMiqfz5l\
d8W+AAAAAAAAAAD34y9AhfWaPwAAAAAAAAAA3qkHQSuARL8AAAAAAAAAAPhVpkIjgc6/AAAAAAAA\
AACNmj8/V79VvwAAAAAAAAAACXkvQGaC3D4AAAAAAAAAAMaoAEL0+I2/AAAAAAAAAAD27v8+XOco\
PwAAAAAAAAAAVJUvQB+ovr4AAAAAAAAAAPSs3z//tKA/AAAAAAAAAAC8zRNBX28ePwAAAAAAAAAA\
XrmPQYVO/b4AAAAAAAAAAHfM/z6PZSe/AAAAAAAAAAALs79AD9+lPwAAAAABAAAALQAAAAAAAAAA\
AAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wEAAAACAAAAAwAAgHXGKr8AAACAAwAAAAQAAAACAACA\
/SfbPwAAAAAFAAAABgAAAAMAAIB8kiY9AQAAgAcAAAAIAAAAAwAAgIC7N8ABAAAACQAAAAoAAAAD\
AACAKiNhvwIAAIALAAAADAAAAAcAAIBajhc/AgAAAA0AAAAOAAAABAAAgGLQKL4DAACA////////\
//8AAAAAMggmvAMAAAAPAAAAEAAAAAMAAID0iz+/BAAAgP//////////AAAAAO9lwzwEAAAA////\
//////8AAAAAs4rYvAUAAIARAAAAEgAAABIAAIAAAAA/BQAAABMAAAAUAAAAAAAAgORu+T4GAACA\
FQAAABYAAAAHAACAg1BTPgYAAAAXAAAAGAAAAAMAAIC0WVs/CAAAgBkAAAAaAAAAAAAAgNgAxL8I\
AAAAGwAAABwAAAAHAACAwLRfvgsAAIAdAAAAHgAAAAUAAIDYRXG+CwAAAB8AAAAgAAAABAAAgH0d\
fz4MAACAIQAAACIAAAAQAACAAADAPwwAAAAjAAAAJAAAAAcAAICYYFtADQAAgCUAAAAmAAAABgAA\
gPJIgr8NAAAAJwAAACgAAAAGAACA1AWnvg4AAIApAAAAKgAAAAgAAIAAAAA/DgAAACsAAAAsAAAA\
BwAAgOCHYT8PAACA//////////8AAAAA0EaZug8AAAD//////////wAAAABYYDI9EAAAgP//////\
////AAAAAGqQZboQAAAA//////////8AAAAApXEdPREAAID//////////wAAAABCCuS7EQAAAP//\
////////AAAAAAHVAr0SAACA//////////8AAAAAIN2NvBIAAAD//////////wAAAADOrYk8EwAA\
gP//////////AAAAANbwJbwTAAAA//////////8AAAAARcErPRQAAID//////////wAAAAAmRIy8\
FAAAAP//////////AAAAAGfM3DwVAACA//////////8AAAAANf92uxUAAAD//////////wAAAAA1\
QDK9FgAAgP//////////AAAAAILp8DsWAAAA//////////8AAAAA/TjqvBcAAID//////////wAA\
AAD/+7y8FwAAAP//////////AAAAADhY6jsYAACA//////////8AAAAAKigWvRgAAAD/////////\
/wAAAAD3kFI89FCPQ9IkckO5vDi+AAAAAABNskCi/odCR/zFPwAAAACIFzRCgCUuQ4IaXL8AAAAA\
gB8ZQDgDhEJ0Qsw/AQAAACejbkC82v4/qS+MvQIAAAB1uEJBu2FtQs9tGL4AAAAAABGxQSOa5UKS\
hZy/AAAAAAAAAACf1H8+xo7HvgAAAAAAMUE/TYODQkP1zT8AAAAAAAAAAKD5fT+E2mo/AAAAAAAA\
AADYu38/HyKCvwAAAABHt9hAOHVJQp+Wr74AAAAASlCsQA6yD0FnaV0/AAAAAEDVnkB8fY9C8/jH\
vwAAAADCbxpBTTksQlByIr8AAAAAgETOP8Udb0JUf9Q/AgAAAICLbkCtRr9AKPRuPwIAAADwfKJA\
33SzQTpJPb8CAAAA2DxOQZF130HM/yO8AgAAANTGEUAJvJ9Ai227PwIAAAC/AYFAJVB/QOSr57wC\
AAAAgBEZQOOHgkJT29K/AgAAACMLZ0CeWc9AQp4ZvwIAAADAzyBBKBrhQQ39ir4CAAAAcN+cQOSw\
bkGnMaG/AgAAAAAAAADYyv4+CTo4vQAAAAAAAAAALyBtQgdl1j8AAAAAAAAAAJ2FH0CO9Qm9AAAA\
AAAAAAC+B19ASTy9PwAAAAAAAAAA+01DQRYLib4AAAAAAAAAAMKbI0EDQJ2/AAAAAAAAAACuZ19B\
ZIIqvwAAAAAAAAAAdINfQb96JT8AAAAAAAAAAMjSfz6ycse+AAAAAAAAAABzvZdArm/OPwAAAAAA\
AAAAErsvQNWWKL8AAAAAAAAAACYqnz/+sIQ/AAAAAAAAAACs8Z4/hm8UvgAAAAAAAAAAHAyAQmc+\
1r8AAAAAAAAAAGjoH0Box5A+AAAAAAAAAADTyn5AP8KMvwAAAAAAAAAAxP1OQQglY78AAAAAAAAA\
AIw2c0EE1Yw+AAAAAAAAAAAHsl5BH3q0vwAAAAAAAAAA0+1/P58V/T4AAAAAAQAAADcAAAAAAAAA\
AAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////8BAAAAAgAAAAMAAIAuM/W+AAAAgAMAAAAEAAAAAwAA\
gPb6Yb8AAAAABQAAAAYAAAAEAACAIHJnvAEAAIAHAAAACAAAAAMAAIAG9T7AAQAAAAkAAAAKAAAA\
AgAAgAComj4CAACACwAAAAwAAAAPAACAAADAPwIAAAANAAAADgAAAAcAAIDion28AwAAgP//////\
////AAAAALwtJbwDAAAADwAAABAAAAAAAACA/nftvwQAAIARAAAAEgAAAAcAAICUAfq+BAAAABMA\
AAAUAAAABQAAgIgUDD4FAACAFQAAABYAAAAQAACAAABgQAUAAAAXAAAAGAAAAAcAAIDuDYY+BgAA\
gBkAAAAaAAAAAwAAgIFNYz8GAAAAGwAAABwAAAAIAACAAAAAPwgAAIAdAAAAHgAAAAAAAIDs5QHA\
CAAAAP//////////AAAAANF6LT0JAACAHwAAACAAAAABAACAtMuavwkAAAAhAAAAIgAAAAQAAIAs\
YyxACgAAgCMAAAAkAAAABAAAgKwN6L0KAAAAJQAAACYAAAANAACAAAAAPwsAAIAnAAAAKAAAAAMA\
AIBLUqg+CwAAACkAAAAqAAAABwAAgMWssb4MAACAKwAAACwAAAAFAACALjAEvgwAAAAtAAAALgAA\
AAMAAIDkTGQ+DQAAgC8AAAAwAAAAAAAAgLxk674NAAAAMQAAADIAAAAMAACAAAAAPw4AAIAzAAAA\
NAAAAAUAAIAgLu8+DgAAADUAAAA2AAAAAwAAgBo1cz8PAACA//////////8AAAAARZeCPA8AAAD/\
/////////wAAAAB9ljO8EQAAgP//////////AAAAAK2Pt7wRAAAA//////////8AAAAAs/UsPBIA\
AID//////////wAAAAAHTA89EgAAAP//////////AAAAAE+0NLwTAACA//////////8AAAAA3YFu\
vBMAAAD//////////wAAAAA8bfU8FAAAgP//////////AAAAAJBYFL0UAAAA//////////8AAAAA\
CwfMOxUAAID//////////wAAAAAgLOW8FQAAAP//////////AAAAAFIxML0WAACA//////////8A\
AAAA8IjavBYAAAD//////////wAAAABMaHs8FwAAgP//////////AAAAACKM6rwXAAAA////////\
//8AAAAAnyXrOxgAAID//////////wAAAAC/fwy8GAAAAP//////////AAAAAItA4TwZAACA////\
//////8AAAAAhQ7wvBkAAAD//////////wAAAACTtfq6GgAAgP//////////AAAAAKNBDr0aAAAA\
//////////8AAAAAtzA7PBsAAID//////////wAAAAAiCDW8GwAAAP//////////AAAAANzh6Dwc\
AACA//////////8AAAAAH48JPRwAAAD//////////wAAAAABwIe86MOAQ8V1ckNeLhu+AAAAABD6\
CUFk6pxCpwKqPwAAAACq1lNCkwAkQzL7XL8AAAAAIJMYQCSbQkIrFsw/AQAAAMwwFEFIc+5BySNb\
PwAAAACQrVhBvnnEQveJqb8AAAAAYseiQWiHg0JsiSi+AAAAAAAAAADhwX8+M4jGvgAAAAAAiUc/\
YptBQsBfzj8BAAAAWOOVQKybtEF8eJQ/AAAAAJa0oUBxXudAP9HyvQAAAABA0ptANjOkQseKvr8A\
AAAAGlepQCAagUE6Nue+AAAAAJ/iF0H0JUxCg13tvgAAAAB4bGBAbqNrQdrRVT8AAAAAD3YyP77y\
Pj9KSWU+AgAAAAAAAACXnz5CYoLQPwAAAAB4PtE/aZ8PQNpDG74CAAAAcEQEQL+nokGMCqc/AgAA\
AO+3jUAZt49A028BPwIAAABGNAlAsU4vQOxxgL8CAAAAgFkmQBw8nkJmi8S/AgAAAFOnTEAv4z5A\
05cvvgIAAADwgVVA2VYiQVK5XL8CAAAACoBpQNC6v0BNBok+AgAAAFjptEBlfSFCBjVpvgIAAACQ\
NAVAOaIqQaZVob8CAAAAJaVcQCfLl0CGfsM9AgAAADhKa0DavR9BBbGSPwIAAAAAAAAAxkL+PtD1\
HD8AAAAAAAAAAGlFfz7M2de+AAAAAAAAAABIRD8/YaBcvwAAAAAAAAAAr5y/P2Pizz4AAAAAAAAA\
AJOpoEFhO6w/AAAAAAAAAAAAFn8+VTHZvgAAAAAAAAAA1JrfP21VD78AAAAAAAAAAMigL0D0fZM/\
AAAAAAAAAABhMv8/6EyyvwAAAAAAAAAAAtY+P7I5dT4AAAAAAAAAAKqrkkFJuYm/AAAAAAAAAABj\
InNCIMXTvwAAAAAAAAAAtPqeP8FUg78AAAAAAAAAAKrL3j8QFhc/AAAAAAAAAADMmAZBN/SMvwAA\
AAAAAAAAaPDdP3RQjT4AAAAAAAAAADSOb0B33qi+AAAAAAAAAABs5w9ALF6HPwAAAAAAAAAAUoOf\
QM1DkL8AAAAAAAAAAPuMDUKoqpa9AAAAAAAAAADDqyZBM/uqvwAAAAAAAAAAWp19PgP94D4AAAAA\
AAAAAEeuX0AVltm+AAAAAAAAAAAR0J8/CvSLPwAAAAAAAAAAGsIXQd5VpT8AAAAAAAAAAP53/z48\
KSO/AAAAAAEAAAAzAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AQAAAAIAAAADAACA\
5J2HvgAAAIADAAAABAAAAAMAAIBaS1i/AAAAAAUAAAAGAAAABAAAgOq1nD4BAACABwAAAAgAAAAD\
AACABvU+wAEAAAAJAAAACgAAAAQAAIAxYY2+AgAAgAsAAAAMAAAABgAAgNQ5/r8CAAAADQAAAA4A\
AAAHAACAXv3HvgMAAID//////////wAAAADhVCS8AwAAAA8AAAAQAAAAAwAAgGlnf78EAACAEQAA\
ABIAAAAGAACALMq1PQQAAAATAAAAFAAAAAEAAIA6Dhc+BQAAgBUAAAAWAAAABAAAgMCHBcAFAAAA\
FwAAABgAAAAEAACAY1ECvwYAAIAZAAAAGgAAAA4AAIAAAAA/BgAAABsAAAAcAAAACAAAgAAAAD8I\
AACA//////////8AAAAAeqsxPQgAAAAdAAAAHgAAAAQAAIDqaI4+CQAAgB8AAAAgAAAACwAAgAAA\
AD8JAAAAIQAAACIAAAAHAACAjDzXvgoAAIAjAAAAJAAAAAEAAIDoBkg9CgAAACUAAAAmAAAAAQAA\
gB+YBEALAACA//////////8AAAAAHYyGvAsAAAD//////////wAAAADk1vw8DAAAgCcAAAAoAAAA\
AQAAgJGyOEAMAAAAKQAAACoAAAACAACA/ISIvw0AAIArAAAALAAAAAcAAIAUNPK+DQAAAC0AAAAu\
AAAADQAAgAAAAD8OAACALwAAADAAAAABAACA0vzWvg4AAAAxAAAAMgAAAAAAAIAkWZe/EAAAgP//\
////////AAAAALz6kDsQAAAA//////////8AAAAAfAghPREAAID//////////wAAAABuyzU8EQAA\
AP//////////AAAAAIACzrwSAACA//////////8AAAAAkPsNPBIAAAD//////////wAAAAD5rQe9\
EwAAgP//////////AAAAAKNhdjwTAAAA//////////8AAAAA92G7vBQAAID//////////wAAAAAa\
wRI9FAAAAP//////////AAAAAGsdBbwXAACA//////////8AAAAABV8pvRcAAAD//////////wAA\
AAD8rz08GAAAgP//////////AAAAAEGvtTsYAAAA//////////8AAAAAi37vvBkAAID/////////\
/wAAAABouAq9GQAAAP//////////AAAAANTmPrwaAACA//////////8AAAAAoTC5PBoAAAD/////\
/////wAAAABYZIa8GwAAgP//////////AAAAAJgiSzwbAAAA//////////8AAAAAY1rLvBwAAID/\
/////////wAAAABL8UW8HAAAAP//////////AAAAAEb21Ty0KG9DdyJyQxTeDL4AAAAAROHLQQIK\
v0LHJIs/AAAAAJCvQUJ2nRJDTvdvvwAAAACABRJA3wpVQsh3xT8BAAAAYyMvQSUJKUJAFPs+AAAA\
ADD+H0FuBNdCWf6jvwAAAADRrX5B/WwcQnIchTwAAAAAAAAAAOSrfz6Og8W+AAAAAACTxT8zC1RC\
8oXHPwEAAADolHNAX1kzQQiKq74AAAAAeDx5QJpl+EHxHko/AAAAAIJ/MECDZ/8/umksPwIAAADA\
lsxA0AbTQm99qb8AAAAAaLZZQE1JjUGjpyq/AAAAAOJ83ECskKtBrE8VPwAAAAAAAAAA/sgpQqOL\
1T8AAAAA6IKTQNQIKUFsl4E/AgAAAA0cQEBTKd9ALlAGPgIAAAD+MhxAbImHQP8ne78CAAAAXo9M\
QLcOn0H30Pc+AgAAAKh2OEDErTJB1N6fPwIAAAAAAAAArj3/Piy3Ib8AAAAAAAAAABiYvz9f8pc/\
AAAAAIDQJ0Bbnl1CeGvJvwIAAAD439RARm9IQm3vgr8CAAAA1AoaQFS7ekFgyVG/AgAAAHyY/T8u\
uv4/QTDRPgIAAACypGNA0LCnQHbBub4CAAAAgFxFQHikgUF7eWQ/AgAAAAAAAACK2o1ADkEuPgAA\
AAAAAAAAHjfEQKmMwT8AAAAAAAAAAMBBv0DQgNo+AAAAAAAAAACUPH8/npt3vwAAAAAAAAAAujI/\
P/mmqj4AAAAAAAAAAClGX0CQE6O/AAAAAAAAAACrEplB1BAUPwAAAAAAAAAAlIE/PzU4Yb8AAAAA\
AAAAALzGJkErY7A/AAAAAAAAAACCcD4/b/6fvgAAAAAAAAAAe6FcQjSSy78AAAAAAAAAAJ3ffD5d\
/eM+AAAAAAAAAABX+21A815aPgAAAAAAAAAAkY85Qkftj78AAAAAAAAAAG0Ot0Auu6a/AAAAAAAA\
AAAeNB9B+XLlvgAAAAAAAAAAfP2+P4aVXj8AAAAAAAAAAMfy/j5ghyG/AAAAAAAAAAB50Q9AHif0\
PgAAAAAAAAAAJpA/QC1qdL8AAAAAAAAAABAGfz9m6e2+AAAAAAAAAACQWHNBO5WAPwAAAAABAAAA\
NwAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wEAAAACAAAAAwAAgOYosb4AAACAAwAA\
AAQAAAADAACAWktYvwAAAAAFAAAABgAAAAQAAID4sKG9AQAAgAcAAAAIAAAABgAAgBLBF0ABAAAA\
CQAAAAoAAAAEAACAs9aCPgIAAIALAAAADAAAAAYAAIAihey/AgAAAA0AAAAOAAAABwAAgHUijDsD\
AACADwAAABAAAAABAACAsGzjvwMAAAARAAAAEgAAAAAAAIAM/iI/BAAAgBMAAAAUAAAABgAAgCzK\
tT0EAAAAFQAAABYAAAACAACA+lVRvwUAAIAXAAAAGAAAAAAAAIB8x42/BQAAABkAAAAaAAAABwAA\
gO4Nhj4GAACAGwAAABwAAAACAACA+3sxvwYAAAAdAAAAHgAAAAIAAID9Rmc/BwAAgB8AAAAgAAAA\
AgAAgPoBhL4HAAAA//////////8AAAAAjTUmPQgAAID//////////wAAAABZCS68CAAAAP//////\
////AAAAAEi/DzwJAACAIQAAACIAAAAFAACA1Ed0vwkAAAAjAAAAJAAAAAAAAIBUbaQ/CgAAgCUA\
AAAmAAAABwAAgJhuh0AKAAAAJwAAACgAAAAQAACAAAAgQAsAAID//////////wAAAABLQZC8CwAA\
ACkAAAAqAAAAAAAAgH7q3z4MAACAKwAAACwAAAABAACA14+EPwwAAAAtAAAALgAAAA8AAIAAAMA/\
DQAAgC8AAAAwAAAABAAAgDY3Tj8NAAAAMQAAADIAAAAEAACAxuxRPw4AAIAzAAAANAAAABAAAIAA\
ACBADgAAADUAAAA2AAAAAQAAgBj0nb8PAACA//////////8AAAAAfIBEvA8AAAD//////////wAA\
AACEuHQ8EwAAgP//////////AAAAAKHairwTAAAA//////////8AAAAAWUSPPBQAAID/////////\
/wAAAADY0OS8FAAAAP//////////AAAAAIN5kzwVAACA//////////8AAAAAP88gPRUAAAD/////\
/////wAAAABKnjO8FgAAgP//////////AAAAADol27sWAAAA//////////8AAAAAcLiuPBgAAID/\
/////////wAAAACht/A8GAAAAP//////////AAAAAOaoKrwZAACA//////////8AAAAAjBsnvRkA\
AAD//////////wAAAAAWN8K8GgAAgP//////////AAAAAO6Z/7waAAAA//////////8AAAAAJGn1\
OxsAAID//////////wAAAACQGS48GwAAAP//////////AAAAAJXLs7wcAACA//////////8AAAAA\
nfDhvBwAAAD//////////wAAAAD5MOK7HQAAgP//////////AAAAAHpD6bsdAAAA//////////8A\
AAAAKz3mPB4AAID//////////wAAAAA9TCg8HgAAAP//////////AAAAAL5A/Lxg+2FD1/51Q8oa\
Lr4AAAAAeKzaQQLOuELSh4c/AAAAAIgk40HWlxlDA1BpvwAAAADAl7k/W6tRQmSjwz8AAAAA8oA1\
QanwH0JDiNc+AAAAAIBvWUHADaxCGSSlvwAAAAB60YJB7CGHQj+q1b4AAAAAAKpwPxayT0KwrsU/\
AQAAAPZ5sD6Bovw+WJ95vQIAAABJVqlAQ2eJQRELQb4AAAAAXOKDQBB6tkF0WF4/AAAAAGD/HUCP\
jE9AMbwSPwEAAABg0NVAXJGlQpo/r78AAAAAWKndQHR1VUK4RSu/AAAAAJJxwECQOWNBFqYCPwAA\
AAAI6DU/+MQ7PxYsJj4CAAAAAAAAAALDTEJJxcc/AAAAAAAAAABO4n8+si3RvgAAAAAAAAAAtGJ5\
PufFrD4AAAAAiB+jQHwyL0Ftpmw+AgAAABCpS0AUOMdAiT1bvwIAAABgtBJAX38CQYantD8CAAAA\
yDaBQMF0akGMt/0+AgAAAAAAAAA8s/8+K2ItvwAAAADsdb4/J5YvQK7Baz8CAAAAgPseQP+1kUKG\
zby/AgAAAJHXykDi2h5BoDgHvwIAAABeT8JAeyhnQcqPkL0CAAAAbL2CQFWrG0K9RGK/AgAAADhy\
mEB5R0dBjHhCPwIAAAAkgL4/uJDfP1SRZb8CAAAAAAAAAGNhej4eLuy+AAAAAAAAAAA+Wfo+WRET\
PwAAAAAAAAAAf3BfQFDkJr8AAAAAAAAAALms7kAmMiw/AAAAAAAAAACGPrdAboKJvwAAAAAAAAAA\
6pj/PtFAMT8AAAAAAAAAAJwE/UDdR8E/AAAAAAAAAAAvRH8+LOPXvgAAAAAAAAAAglaPQK6yg74A\
AAAAAAAAAIDJIkEkAFI/AAAAAAAAAAAqlh9AbqmQPwAAAAAAAAAA1/9/PrIezb4AAAAAAAAAAOeR\
c0K52ci/AAAAAAAAAABhaD9BhG5pvwAAAAAAAAAAtgSmQEabmb8AAAAAAAAAAA6xl0B+e5M+AAAA\
AAAAAADBYhNBL0HRPgAAAAAAAAAAc4unQJ0ZWL8AAAAAAAAAAP2f7UH8x4e/AAAAAAAAAABcbRNB\
qe6HvgAAAAAAAAAA/k0/QLQujL4AAAAAAAAAAPlzF0FgXYo/AAAAAAAAAAAJ9n8+8EfKPgAAAAAA\
AAAA95G/PyOYl78AAAAAAQAAACkAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////8BAAAA\
AgAAAAMAAIBPLzG/AAAAgAMAAAAEAAAAAAAAgP537b8AAAAABQAAAAYAAAADAACAfJImPQEAAID/\
/////////wAAAACQ+Dm8AQAAAAcAAAAIAAAAAgAAgP34J0ACAACACQAAAAoAAAABAACAepRJPgIA\
AAALAAAADAAAAAcAAIAfmJe+BAAAgA0AAAAOAAAABgAAgD8uHEAEAAAA//////////8AAAAAdYUl\
vAUAAIAPAAAAEAAAAAYAAIAsyrU9BQAAABEAAAASAAAAEgAAgAAAAD8GAACAEwAAABQAAAAEAACA\
MadAvgYAAAAVAAAAFgAAAAQAAIBYOEM/BwAAgP//////////AAAAABvTIj0HAAAAFwAAABgAAAAA\
AACADP4iPwkAAIAZAAAAGgAAAAUAAIAGH36/CQAAABsAAAAcAAAAAgAAgPnNe78KAACAHQAAAB4A\
AAAQAACAAAAgQAoAAAAfAAAAIAAAAAAAAICsoEi/CwAAgCEAAAAiAAAADwAAgAAAIEALAAAAIwAA\
ACQAAAAFAACAEJSMvgwAAIAlAAAAJgAAAAEAAIA3WdA/DAAAACcAAAAoAAAABQAAgMwjSUAOAACA\
//////////8AAAAA+h8tvA4AAAD//////////wAAAABGDg88DwAAgP//////////AAAAALC8Br0P\
AAAA//////////8AAAAAbbzzOxAAAID//////////wAAAACLYgo8EAAAAP//////////AAAAAC2X\
BL0RAACA//////////8AAAAA1LXUvBEAAAD//////////wAAAABui0s8EgAAgP//////////AAAA\
AJhOaLwSAAAA//////////8AAAAA3u0APRMAAID//////////wAAAABMdSa9EwAAAP//////////\
AAAAAPaHRjwUAACA//////////8AAAAArvOTuxQAAAD//////////wAAAAA7Gwe9FQAAgP//////\
////AAAAAAjNybwVAAAA//////////8AAAAAVFV8PBYAAID//////////wAAAADQnsk8FgAAAP//\
////////AAAAAOKyrLzwTV5DLbdwQw6G+70AAAAAwOcaQFaTeUJcYb4/AQAAAKJEQEJXUjJDlvww\
vwAAAAAAAAAAG/F9PtSF374AAAAAQD0OQGWVeEJ+O8A/AQAAALBePkGiXnlCLuuPPAAAAAAQd3RB\
XfXnQkzfiL8AAAAAADm2P5uVd0Lw+8E/AQAAAAAAAADPyX8+ovHGvgAAAADcUxhBdCMFQuJMxb4A\
AAAAfe3fQFx26EE3APQ+AAAAAMCiUkBEko1CdQKuvwAAAABiAVdBM8Y0QuVkGL8AAAAAAAAAAKSc\
dULjs8M/AAAAADCurj5ne/w+UT94vQIAAACZwNNAbhefQV0vdj0CAAAAoh+gQPVeVkGjnIC/AgAA\
AFRN50C/zT5BNcngvQIAAABL/hZBfQ+JQexDXj8CAAAAABIqQDuLNEK7Z8W/AgAAACQDukCaMs1B\
jfR9vwIAAACMYftAft4aQkYxUb8CAAAAvB95QKM9z0BBuik/AgAAAAAAAABF738+MxXQvgAAAAAA\
AAAAiQd5Pijxqz4AAAAAAAAAADiIDkCO8aG/AAAAAAAAAABnRo1B2nmSPgAAAAAAAAAAN43/P/pT\
pj4AAAAAAAAAAE5tNkEWXZ+/AAAAAAAAAAD/845AUKl/vwAAAAAAAAAAgKfuQB+l9D4AAAAAAAAA\
ACNsTkCKmwu/AAAAAAAAAADxg15Bg/aaPwAAAAAAAAAAuZEzQucRyL8AAAAAAAAAAIGCeT59nu4+\
AAAAAAAAAAA0htxAp9MxvgAAAAAAAAAADRGWQTFjor8AAAAAAAAAAN32DkKWjHK/AAAAAAAAAAAZ\
ej5AgqQXPwAAAAAAAAAAcGW3QAhVcj8AAAAAAAAAAJfBPj8Ukk+/AAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABxI4VxJFJxJVgHAAAAYm9vc3RlcnEmWAYAAABnYnRy\
ZWVxJ1gOAAAAYmVzdF9pdGVyYXRpb25xKEsJWBAAAABiZXN0X250cmVlX2xpbWl0cSlLCnViLg=="
